#
# Ubuntu Dockerfile
#
# https://github.com/dockerfile/ubuntu
#
# Pull base image.
FROM ubuntu:latest
MAINTAINER Lex@snsyr.com
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
# Install.
RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential && \
  apt-get install -y software-properties-common && \
  apt-get install -y byobu curl git htop man unzip vim wget bind9-host sysdig iputils-arping iputils-ping hping3 netcat-traditional tcptraceroute mtr traceroute bind9-dnsutils dnsutils apache2-utils siege && \
  rm -rf /var/lib/apt/lists/*


# Add files.
#ADD root/.bashrc /root/.bashrc
#ADD root/.gitconfig /root/.gitconfig
#ADD root/.scripts /root/.scripts
# Set environment variables.
#ENV HOME /root
# Define working directory.
#WORKDIR /root


# Define default command.
CMD ["bash"]
